package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-OqY7zN/openjdk-8-8u222-b10/src/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, July 18, 2019 8:39:37 PM UTC
*/

public interface TransactionService
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CosTSInteroperation.PropogationContext</code> defined in 
       * <i>CORBAservices: Common Object Services Specifications.</i>
       */
  public static final int value = (int)(0L);
}
