package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-OqY7zN/openjdk-8-8u222-b10/src/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, July 18, 2019 8:39:36 PM UTC
*/

public interface IIOP_CLEAR_TEXT
{

  /** Possible values for endpointType argument on Server.getEndpoint()
      * If you change the value of this constant then update
      * core.EndPoint accordingly.  It has a duplicate definition
      * to avoid a compilation dependency.
      */
  public static final String value = "IIOP_CLEAR_TEXT";
}
