package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-8-OqY7zN/openjdk-8-8u222-b10/src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, July 18, 2019 8:39:37 PM UTC
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
     */
  public static final short value = (short)(2);
}
